End ‘register ECT’ journey if teacher is exempt from induction
DFE-Digital/register-early-career-teachers pull request #816
Opened 2024-11-26 16:44 UTC by TobyRet

### Ticket
#688 

### Changes
- Add test data for 'exempt' teacher in TestGuidance component
- If a teacher is exempt from induction, the user is redirected to a new error page

### Video

2024-11-27 09:26 UTC, ltello requested changes
Good job Toby, just a few suggestions

2024-11-27 09:26 UTC, ltello commented on app/wizards/schools/register_ect/find_ect_step.rb
>          :review_ect_details
Wouldn't be better to reorder sentences like this:

```
def next_step
  return :trn_not_found unless ect.in_trs?
  return :national_insurance_number unless ect.matches_trs_dob?
  return :induction_completed if ect.induction_completed?
  return :induction_exempt if ect.induction_exempt? 

  :review_ect_details
end
```

2024-11-27 09:26 UTC, ltello commented on app/wizards/schools/register_ect/find_ect_step.rb
> +                   trs_induction_exempt?: trs_teacher.induction_status == 'Exempt')
Wouldn't be better to just save `trs_induction_status` and put the logic for 
`trs_induction_completed?: trs_teacher.induction_status == 'Pass'` and 
`trs_induction_exempt?: trs_teacher.induction_status == 'Exempt'`
in Schools::RegisterECT::ECT class?

2024-11-27 09:26 UTC, ltello commented on app/wizards/schools/register_ect/national_insurance_number_step.rb
> +        return :induction_exempt if ect.induction_exempt? && ect.matches_trs_national_insurance_number?
I think we don't need to check for `&& ect.matches_trs_national_insurance_number?` in these 2 sentences because if `ect.in_trs?` is true is because TRS returned a record that matches both the TRN and the NINO.
So at this point `ect.matches_trs_national_insurance_number?` will always be true.
Actually we can even delete this method `matches_trs_national_insurance_number?`

2024-11-27 09:26 UTC, ltello commented on app/wizards/schools/register_ect/national_insurance_number_step.rb
>        end
Same as above

2024-11-27 09:26 UTC, ltello commented on config/routes.rb
maybe we can remove this blank line for the routes file not to become huge and less readable?

2024-11-27 09:30 UTC, claire-hughez commented on app/views/schools/register_ect/induction_exempt.html.erb
> +<p class="govuk-body">Our records show <%= @ect.full_name %> is exempt from having to serve induction so you cannot register them for ECF training.</p>
```suggestion
<p class="govuk-body">Our records show <%= @ect.full_name %> is exempt from having to serve induction and therefore cannot be registered as an ECT.</p>
```

2024-11-27 09:39 UTC, TobyRet commented on app/views/schools/register_ect/induction_exempt.html.erb
> +<p class="govuk-body">Our records show <%= @ect.full_name %> is exempt from having to serve induction so you cannot register them for ECF training.</p>
Cool - have made the change to this page and the 'induction completed' error page also

2024-11-27 12:02 UTC, TobyRet commented on app/wizards/schools/register_ect/find_ect_step.rb
> +                   trs_induction_exempt?: trs_teacher.induction_status == 'Exempt')
Yes good point. I have moved the logic.

2024-11-27 12:07 UTC, TobyRet commented on app/wizards/schools/register_ect/national_insurance_number_step.rb
> +        return :induction_exempt if ect.induction_exempt? && ect.matches_trs_national_insurance_number?
Good spot. I've removed. At this point we have already queried the TRS API with the trn and NINO so if we get something back we do not need to check again.

2024-11-27 16:06 UTC, ltello requested changes
Just one change left I guess

2024-11-27 16:06 UTC, ltello commented on app/wizards/schools/register_ect/find_ect_step.rb
>          :review_ect_details
This ☝️

2024-11-28 10:08 UTC, TobyRet commented on app/wizards/schools/register_ect/find_ect_step.rb
>          :review_ect_details
557b40de279667c4a6b6771d8dc9b657b06e8587

2024-11-28 13:50 UTC, merged